name: CI Pipeline

on:
  push:
    branches:
      - test
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install Dependencies
        run: |
          cd src
          npm install

      - name: Install Stylelint Config
        run: npm install --save-dev stylelint-config-standard
        
      - name: Run lint
        run: |
          cd src
          npm run lint

      - name: Run HTMLHint
        run: |
          cd src
          npm run htmlhint
          
      - name: Run Stylelint
        run: |
          cd src
          stylelint "statics/**/*.css"

      - name: Run Unit Tests
        run: |
          npm test
