name: CI Pipeline

on:
  push:
    branches:
      - test
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm install
          
      - name: Run tests
        run: |
          npm run lint
          npm run htmlhint
          npm run lint:css

      - name: Run Unit Tests
        run: |
          npm test
